version: 2
jobs:
  build:
    machine: true
    # CircleCI 2.0 does not support environment variables that refer to each other the same way as 1.0 did.
    # If any of these refer to each other, rewrite them so that they don't or see https://circleci.com/docs/2.0/env-vars/#interpolating-environment-variables-to-set-other-environment-variables .
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - checkout
      - run: docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker build -t everhartlab/sclerotinia-366 .
          no_output_timeout: 1800s
      - run: docker run -ti -v $(pwd):/tmp -w /tmp everhartlab/sclerotinia-366 ./tests.sh
      - run: docker run --name sclerotinia-366 -d -p 8787:8787 everhartlab/sclerotinia-366 ; sleep 10
      - run: curl --retry 10 --retry-delay 5 -v http://localhost:8787
      # Save test results
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
# https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
workflows:
  version: 2
  un-tagged-build:
    jobs:
      - build
      - deploy:
          steps:
            - run: docker push everhartlab/sclerotinia-366
        filters:
          tags:
            ignore: /^v.*/
      branches:
        only: /(master|update-circle)/
  tagged-build:
    jobs:
      - build
      - deploy:
          steps:
            - run: docker tag everhartlab/sclerotinia-366 everhartlab/sclerotinia-366:${CIRCLE_TAG}
            - run: docker push everhartlab/sclerotinia-366:${CIRCLE_TAG}
        tags:
          only: /^v.*/
        filters:
          branches:
            ignore: /.*/
# deployment:
#   hub:
#     branch: master
#     commands:
#       - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#       - docker push everhartlab/sclerotinia-366
#   hubtag:
#     branch: master
#     tag: /.*?/
#     commands:
#       - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#       - docker tag everhartlab/sclerotinia-366 everhartlab/sclerotinia-366:${CIRCLE_TAG}
#       - docker push everhartlab/sclerotinia-366:${CIRCLE_TAG}
